### ISSUE TITLE
coffee types mls

### ISSUE THREAD

**Issue by kerusey** [kerusey/CoffeeBreaker#49]
cappuccino : 200, 300
milk (additional): 100
espresso: 30, 60
crema: 100, 200
latte macchiato: 200, 400
milkcoffee: 200, 400

**Comment by syorito-hatsuki** [comment]
Если у молока ток 1 вариант, то в таком случае канает и простой CheckBox?

**Comment by kerusey** [comment]
Да, но сделайте его не вырвиглазным

**Comment by syorito-hatsuki** [comment]
> Да, но сделайте его не вырвиглазным

Молоко [x]

**Comment by kerusey** [comment]
Ну тип если это будет уродский кусок говна, который работает через раз, то не катит

**Comment by syorito-hatsuki** [comment]
> Ну тип если это будет уродский кусок говна, который работает через раз, то не катит

Работать будет без Б, а вот говно ли, я пока хз

**Comment by kerusey** [comment]
Ну слушай, ну узнай =)

**Comment by llav3ji2019** [comment]
Можно вообще не парится и сделать TextView. Когда молоко выберет пользователь, то поставим 0,1 Л, а кнопки visible=false( чтобы выбрать не смог и не мешались на экране). А когда кофе выберет, то у нас TextView с пустым тестом или visible=false. А ещё можно enabled=false поставить при выборе молока (кнопку Большая кружка заблочить, чтобы был доступен один объём  ) и тогда минимум изменений. Короче вариантов много)

**Comment by syorito-hatsuki** [comment]
> Можно вообще не парится и сделать TextView. Когда молоко выберет пользователь, то поставим 0,1 Л, а кнопки visible=false( чтобы выбрать не смог и не мешались на экране). А когда кофе выберет, то у нас TextView с пустым тестом или visible=false. А ещё можно enabled=false поставить при выборе молока (кнопку Большая кружка заблочить, чтобы был доступен один объём ) и тогда минимум изменений. Короче вариантов много)

Утром отпишу своё мировозрение, ток это ты явно не в тот Issues написал :D
